FROM golang:latest

RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

WORKDIR /migrations

ENTRYPOINT ["sh", "-c", "migrate -path /migrations -database ${DB_URL} up"]