version: '3.8'


services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: migrate_container
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
    volumes:
      - ./migrations:/migrations
    
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: app_container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "3000:3000"
      - "9000:9000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: postgres

volumes:
  postgres_data: